name: school-stack

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: school-stack-app
    container_name: school-app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env.docker
    environment:
      TZ: Asia/Makassar
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ./:/var/www
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: school-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend

  db:
    image: mariadb:11
    container_name: school-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: school
      MARIADB_USER: school
      MARIADB_PASSWORD: school
      MARIADB_ROOT_PASSWORD: root
      TZ: Asia/Makassar
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: school-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - backend

volumes:
  db_data:
  redis_data:

networks:
  frontend:
  backend:
